sudo: false

language: cpp

osx_image: xcode6.4

os:
  - osx

compiler:
  - clang

env:
  global:
    - PATH=${TRAVIS_BUILD_DIR}/python/bin:$PATH
    - PLATFORM=${TRAVIS_OS_NAME}
    - ARCHFLAGS="-arch x86_64"

virtualenv:
  system_site_packages: true

# Successful builds are archived and uploaded to S3 for bamboo releases.
before_deploy:
  - "PLATFORM='darwin'"
  - cd $TRAVIS_BUILD_DIR
  - ./ci/travis/before_deploy.sh
  - cp $TRAVIS_BUILD_DIR/bindings/py/requirements.txt $TRAVIS_BUILD_DIR/bindings/py/dist/
  - mkdir -p $TRAVIS_BUILD_DIR/bindings/py/dist/include/nupic
  - cp ${TRAVIS_BUILD_DIR}/build/release/include/nupic/Version.hpp $TRAVIS_BUILD_DIR/bindings/py/dist/include/nupic
  - mkdir -p $TRAVIS_BUILD_DIR/bindings/py/dist/bin
  - cp ${TRAVIS_BUILD_DIR}/build/release/bin/py_region_test $TRAVIS_BUILD_DIR/bindings/py/dist/bin
  - mkdir -p $TRAVIS_BUILD_DIR/release
  - tar -zcvf $TRAVIS_BUILD_DIR/release/nupic_core-${TRAVIS_COMMIT}-${PLATFORM}64.tar.gz $TRAVIS_BUILD_DIR/bindings/py/dist

before_install:
  - ". ./ci/travis/before_install-osx.sh"

install:
  - "mkdir -p $TRAVIS_BUILD_DIR/build/scripts"
  - "cd $TRAVIS_BUILD_DIR/build/scripts"
  - "mkdir -p $TRAVIS_BUILD_DIR/build/release"
  - "cmake --version"
  # Enable test coverage for travis-ci build
  - "cmake $TRAVIS_BUILD_DIR -DNTA_COV_ENABLED=ON -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/build/release -DPY_EXTENSIONS_DIR=$TRAVIS_BUILD_DIR/bindings/py/src/htmresearch_core"
  # Configure bash such that a failure in any link in the pipe causes the whole pipe to fail
  - "set -o pipefail"
  - "VERBOSE=1 make|grep -v -F '\\-\\- Installing:'"
  - "make install 2>&1|grep -v -F 'Installing:'"
  - "cd $TRAVIS_BUILD_DIR"
  - "python setup.py install --user"

script:
  - "cd $TRAVIS_BUILD_DIR"
  # run python tests
  - "py.test ${TRAVIS_BUILD_DIR}/bindings/py/tests"
